language: python

python:
    - "3.6"

services:
  - postgresql

# install dependencies
install: 
  - pip install -r requirements.txt
  - psql -c 'create database fast_foods_fast;' -U postgres

# command to run tests
script:
  - pytest -v --cov app --cov-report term-missing
  - coverage report

after_success:
- coveralls